### ISSUE TITLE
kotlin support

### ISSUE THREAD

**Issue by hasanelfalakiy** [gmiller123456/vsop87-multilang#4]
please add support for kotlin language

**Comment by gmiller123456** [comment]
I added a Kotlin CSV version.  Unfortunately an inline version failed with a "Method too large" error.  The files to use with the CSV version are in the Languages/CSV folder.

**Comment by hasanelfalakiy** [comment]
> I added a Kotlin CSV version.  Unfortunately an inline version failed with a "Method too large" error.  The files to use with the CSV version are in the Languages/CSV folder.

OK, thanks, but what does inline version mean?

**Comment by gmiller123456** [comment]
Inline just means all of the constants are part of the code, the CSV version loads them from a file.

**Comment by hasanelfalakiy** [comment]
> Inline just means all of the constants are part of the code, the CSV version loads them from a file.

ok, do you provide the ELP2000/82 method for lunar coordinate data too?

**Comment by gmiller123456** [comment]
Yes.  It has all of the same data.

**Comment by hasanelfalakiy** [comment]
> Yes.  It has all of the same data.

OK, can I have your telegram address? so that I can contact you if there is something I don't understand

**Comment by gmiller123456** [comment]
I can't really offer personalized support.  If you have questions related to this project, you can post them in the discussion tab.

**Comment by hasanelfalakiy** [comment]
> I can't really offer personalized support.  If you have questions related to this project, you can post them in the discussion tab.

oke I see
